export const GET_CAMPINGS_BY_PAGEID_REQUEST = "CAMPINGS/GET_CAMPINGS_BY_PAGEID_REQUEST";
export const GET_CAMPINGS_BY_PAGEID_SUCCESS = "CAMPINGS/GET_CAMPINGS_BY_PAGEID_SUCCESS";
export const GET_CAMPINGS_BY_PAGEID_FAILURE = "CAMPINGS/GET_CAMPINGS_BY_PAGEID/FAILURE";
export const GET_CAMPING_BY_ID_REQUEST = "CAMPINGS/GET_CAMPING_BY_ID_REQUEST";
export const GET_CAMPING_BY_ID_SUCCESS = "CAMPINGS/GET_CAMPING_BY_ID_SUCCESS";
export const GET_CAMPING_BY_ID_FAILURE = "CAMPINGS/GET_CAMPING_BY_ID_FAILURE";
