export const GET_CAMPINGS_REQUEST = "CAMPINGS/GET_CAMPINGS_REQUEST";
export const GET_CAMPINGS_SUCCESS = "CAMPINGS/GET_CAMPINGS_SUCCESS";
export const GET_CAMPINGS_FAILURE = "CAMPINGS/GET_CAMPINGS/FAILURE";